[package]
name = "sbom-common"
version = "0.3.0"
edition = "2024"

[dependencies]
sha2 = { version = "=0.10.8", default-features = false }
risc0-zkvm = { version = "^3.0.3", optional = true, default-features = false }

[features]
default = ["std"]
std = ["risc0-zkvm"]

